# Generated by Django 3.2.7 on 2021-09-25 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210925_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_course', to='myapi.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(blank=True, to='myapi.Branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='myapi.Contact'),
        ),
    ]
