# Generated by Django 3.2.7 on 2021-09-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210925_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_course',
        ),
        migrations.AddField(
            model_name='category',
            name='category_course',
            field=models.ManyToManyField(blank=True, related_name='category_course', to='myapi.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.category'),
        ),
    ]
