# Generated by Django 3.2.7 on 2021-09-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20210925_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_course',
        ),
    ]
