# Generated by Django 3.2.7 on 2021-09-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(blank=True, null=True, to='myapi.Branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='myapi.Contact'),
        ),
    ]
