# Generated by Django 3.2.7 on 2021-09-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20210925_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='course',
            name='contacts',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='myapi.course'),
        ),
    ]
