# Generated by Django 3.2.7 on 2021-09-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20210925_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='myapi.course'),
        ),
    ]
