# Generated by Django 3.2.7 on 2021-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_alter_contact_contact_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='imgpath',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
