# Generated by Django 3.2.7 on 2021-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20210925_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_course',
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(to='myapi.Branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(to='myapi.Contact'),
        ),
    ]
