# Generated by Django 3.2.7 on 2021-09-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20210925_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_course', to='myapi.course'),
        ),
    ]
