# Generated by Django 3.2.7 on 2021-09-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_remove_category_category_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_course',
        ),
    ]
