# Generated by Django 3.2.7 on 2021-09-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_contact_contact_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branches',
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.branch'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='contacts',
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.contact'),
        ),
    ]
