# Generated by Django 3.2.7 on 2021-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_auto_20210925_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branches',
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(to='myapi.Branch'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='contacts',
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(to='myapi.Contact'),
        ),
    ]
