# Generated by Django 3.2.7 on 2021-09-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_auto_20210925_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_course',
        ),
    ]
